export const SET_STROKE_SIZE = 'SET_STROKE_SIZE';
export const SET_TOOL_TYPE = 'SET_TOOL_TYPE';
export const SET_COLOR_PRIMARY = 'SET_COLOR_PRIMARY';
export const SET_COLOR_SECONDARY = 'SET_COLOR_SECONDARY';
export const SWAP_SELECTED_COLORS = 'SWAP_COLORS';
export const SHOW_COLOR_SELECTOR_PRIMARY = 'SHOW_COLOR_SELECTOR_PRIMARY';
export const SHOW_COLOR_SELECTOR_SECONDARY = 'SHOW_COLOR_SELECTOR_SECONDARY';
export const REMOVE_COLOR_SELECTORS = 'REMOVE_COLOR_SELECTORS';

export const SET_DRAWING = 'SET_DRAWING';
export const SET_CANVAS_CTX = 'SET_CANVAS_CTX';

export const SET_PIXEL_SIZE = 'SET_PIXEL_SIZE';
export const SET_FRAME_RATE = 'SET_FRAME_RATE';
export const TOGGLE_SAVE_MODAL = 'TOGGLE_SAVE_MODAL';
export const TOGGLE_LOAD_MODAL = 'TOGGLE_LOAD_MODAL';

export const ADD_FRAME = 'ADD_FRAME';
export const UPDATE_FRAME = 'UPDATE_FRAME';
export const CHANGE_INDEX = 'CHANGE_INDEX';
export const DELETE_FRAME = 'DELETE_FRAME';
export const DUPLICATE_FRAME = 'DUPLICATE_FRAME';
export const MOVE_FRAME = 'MOVE_FRAME';
export const SET_DRAGGING_FRAME = 'SET_DRAGGING_FRAME';
export const CLEAR_FRAMES = 'CLEAR_FRAMES';

export const SET_ALL_SHORTCUTS = 'SET_ALL_SHORTCUTS';
export const SET_SHORTCUT = 'SET_SHORTCUT';
export const TOGGLE_SHORTCUTS_MODAL_VISIBILITY = 'TOGGLE_SHORTCUTS_MODAL_VISIBILITY';
export const TOGGLE_SHORTCUT_EDIT = 'TOGGLE_SHORTCUT_EDIT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERROR';

export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const SET_CURRENT = 'SET_CURRENT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const PROJECT_ERROR = 'PROJECT_ERROR';
export const CLEAR_PROJECTS = 'CLEAR_PROJECTS';
