export const SET_STROKE_SIZE = 'SET_STROKE_SIZE';
export const SET_TOOL_TYPE = 'SET_TOOL_TYPE';
export const SET_COLOR_PRIMARY = 'SET_COLOR_PRIMARY';
export const SET_COLOR_SECONDARY = 'SET_COLOR_SECONDARY';
export const SWAP_SELECTED_COLORS = 'SWAP_COLORS';
export const SHOW_COLOR_SELECTOR_PRIMARY = 'SHOW_COLOR_SELECTOR_PRIMARY';
export const SHOW_COLOR_SELECTOR_SECONDARY = 'SHOW_COLOR_SELECTOR_SECONDARY';
export const REMOVE_COLOR_SELECTORS = 'REMOVE_COLOR_SELECTORS';

export const SET_DRAWING = 'SET_DRAWING';
export const SET_CANVAS_CTX = 'SET_CANVAS_CTX';

export const SET_PIXEL_SIZE = 'SET_PIXEL_SIZE';
export const SET_FRAME_RATE = 'SET_FRAME_RATE';

export const ADD_FRAME = 'ADD_FRAME';
export const UPDATE_FRAME = 'UPDATE_FRAME';
export const CHANGE_INDEX = 'CHANGE_INDEX';
export const DELETE_FRAME = 'DELETE_FRAME';
export const DUPLICATE_FRAME = 'DUPLICATE_FRAME';
export const MOVE_FRAME = 'MOVE_FRAME';
export const SET_DRAGGING_FRAME = 'SET_DRAGGING_FRAME';
export const CLEAR_FRAMES = 'CLEAR_FRAMES';

export const SET_SHORTCUT = 'SET_SHORTCUT';
export const TOGGLE_SHORTCUTS_MODAL_VISIBILITY = 'TOGGLE_SHORTCUTS_MODAL_VISIBILITY';
export const TOGGLE_SHORTCUT_EDIT = 'TOGGLE_SHORTCUT_EDIT';
