export const SET_STROKE_SIZE = 'SET_STROKE_SIZE';
export const SET_TOOL_TYPE = 'SET_TOOL_TYPE';
export const SET_COLOR_PRIMARY = 'SET_COLOR_PRIMARY';
export const SET_COLOR_SECONDARY = 'SET_COLOR_SECONDARY';
export const SWAP_SELECTED_COLORS = 'SWAP_COLORS';
export const SHOW_COLOR_SELECTOR_PRIMARY = 'SHOW_COLOR_SELECTOR_PRIMARY';
export const SHOW_COLOR_SELECTOR_SECONDARY = 'SHOW_COLOR_SELECTOR_SECONDARY';
export const REMOVE_COLOR_SELECTORS = 'REMOVE_COLOR_SELECTORS';

export const SET_PIXEL_SIZE = 'SET_PIXEL_SIZE';
export const SET_FRAME_RATE = 'SET_FRAME_RATE'
